### ISSUE TITLE
Readme and Example.ino use incorrect calls and arg type

### ISSUE THREAD

**Issue by rrzadzki** [WesWedding/TweenDuino#21]
The README and Example.ino both create `TweenDuino *tween`, which is invalid and leads to "does not name a type" errors. The `double value` is implicitly cast to a float, making it a temp value and so "non-const lvalue" errors are thrown. Changing the type of tween to TweenDuino::Tween*, making value a double, and changing the constructor to TweenDuino::Tween::to resolves this.

I forked and created PR20 with these fixes: https://github.com/WesWedding/TweenDuino/pull/20

**Comment by WesWedding** [comment]
Thanks for this; the examples and documentation in general could really use some fixing up (see: #9).  This is a good step along that path!

**Comment by WesWedding** [comment]
Pull request (#20) accepted.
