### ISSUE TITLE
Finalize Docs

### ISSUE THREAD

**Issue by WesWedding** [WesWedding/TweenDuino#9]
Docs need the following...

* General Reorganizing and ToC
* Usage Example
* Accurate Installation Guide
* Timeline and Tween memory use estimates and guidance on reducing footprint
* Illustrate how to switch Easing

**Comment by JasXSL** [comment]
Any chance you could also add an example of easing? I can't figure out how to add it.

**Comment by WesWedding** [comment]
Do you mean an example demonstrating how to just ease a variable from the number "100" to "10" over a period of time?  

Or do you mean changing the [easing function](http://easings.net/) being used from linear to something else?

**Comment by JasXSL** [comment]
Changing the easing function yes.

I'm pretty new to Arduino stuff, tried something like this. It compiles but doesn't work (it jumps directly to a value without tweening)
<pre>
TweenDuino::Tween::Ease ease = TweenDuino::Tween::SINE;
TweenDuino::Tween::EaseType easeType = TweenDuino::Tween::INOUT;
TweenDuino::Tween* tw = TweenDuino::Tween::to(_duty, (float)v, duration, ease, easeType);
timeline.add(*tw);
</pre>

This works but, but doesn't ease:
<pre>
timeline.addTo(_duty, (float)v, duration);
</pre>

**Comment by JasXSL** [comment]
For now I added to Timeline.cpp which works fine:
```
TweenDuino::Tween* TweenDuino::Timeline::addTo(float& target, float to, unsigned long duration, TweenDuino::Tween::Ease e, TweenDuino::Tween::EaseType type) {
    Tween* tween = TweenDuino::Tween::to(target, duration, to, e, type);
    add(*tween);
    return tween;
}
```

Still not sure how to do it any other way.

**Comment by WesWedding** [comment]
Unfortunately the support for actually switching to a non-linear easing isn't completely implemented yet. (See #4)   You get stuck with the default of a linear ease.

If even linear isn't working, have you also added this to your `loop()` function?

```
    uint32_t time = millis();

    // Tell the tween that time has changed and to adjust its calculations.
    timeline.update(time);
```

Switching to a non-linear easing is very close to done, if I remember correctly.  It was the last thing I was working on before other projects dragged me away!  I'll spend some time tonight re-acquainting myself with those unfinished commits and see if I can't get that functionality finished.

**Comment by WesWedding** [comment]
Just saw your most recent comment.

Maybe I busted something in one of my last commits, I'll take a look!

**Comment by WesWedding** [comment]
Hi @JasXSL 
I've circled back to this and
```
TweenDuino::Tween::Ease ease = TweenDuino::Tween::SINE;
TweenDuino::Tween::EaseType easeType = TweenDuino::Tween::INOUT;
TweenDuino::Tween* tw = TweenDuino::Tween::to(_duty, (float)v, duration, ease, easeType);
timeline.add(*tw);
```
works okay for me.
Maybe it's an architecture-specific bug I can't make happen here. 😦 

I also added your method to the lib in [a2e20c21d955d971dd1aa2900ac2b916562b20a7], it was a good idea!

**Comment by WesWedding** [comment]
Improve doc to include some decent copywriting, too...

Here's your problem
• Here's the benefit of solving it
• Here's why what you've tried has failed
• And by the way here's a product that will help you solve it

**Comment by WesWedding** [comment]
This doesn't need to keep holding up forward movement on actually listing this on the libraries index.  Docs could certainly be better, sure, but they're not terrible.
